name: 'Auto Approve'
description: 'Automatic approval of GitHub Actions'
branding:
  icon: 'check'
  color: 'green'
inputs:
  pat_token:
    description: 'GitHub Bot Token'
    required: true
  environment:
    type: environment
    description: 'Environment'
    required: true
runs:
  using: 'node16'
  main: 'app/index.js'